version: '3'
networks:
  dotnet:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 173.17.0.0/16
services:
  web:
    image: jwtredisnetcoreapimg
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    depends_on:
      - redis
    networks:
      dotnet:
        ipv4_address: 173.17.0.7
    tty: true
    links:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_volume:/data
    networks:
      dotnet:
        ipv4_address: 173.17.0.6




